# Base image
FROM ubuntu:22.04

# Define arguments
ARG JDBC_DATABASE_URL
ARG JDBC_USERNAME
ARG JDBC_PASSWORD
ARG DEFAULT_USER_NAME
ARG DEFAULT_USER_PASS
ARG JWT_SECRET
ARG JWT_EXPIRATION
ARG JWT_ISSUER
ARG JWT_AUDIENCE
ARG JWT_MAX_TOKEN_LENGTH
ARG OPENAI_API_KEY
ARG OPENAI_MAX_DAILY_REQUESTS

# Set environment variables
ENV JDBC_DATABASE_URL $JDBC_DATABASE_URL
ENV JDBC_USERNAME $JDBC_USERNAME
ENV JDBC_PASSWORD $JDBC_PASSWORD
ENV DEFAULT_USER_NAME $DEFAULT_USER_NAME
ENV DEFAULT_USER_PASS $DEFAULT_USER_PASS
ENV JWT_SECRET $JWT_SECRET
ENV JWT_EXPIRATION $JWT_EXPIRATION
ENV JWT_ISSUER $JWT_ISSUER
ENV JWT_AUDIENCE $JWT_AUDIENCE
ENV JWT_MAX_TOKEN_LENGTH $JWT_MAX_TOKEN_LENGTH
ENV OPENAI_API_KEY $OPENAI_API_KEY
ENV OPENAI_MAX_DAILY_REQUESTS $OPENAI_MAX_DAILY_REQUESTS

# Install OpenJDK 17 slim
RUN apt-get update && \
    apt-get install -y openjdk-17-jdk-headless && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . .

# IMPORTANT, if this line fails because GitHub Action cannot find mvnw,
# it is because the wrapper is not available within the repository.
# Ensure you doesn't ignore the wrapper in .gitignore.
RUN chmod +x mvnw
RUN ./mvnw package

EXPOSE 8080

CMD ["sh", "-c", "java -jar target/backend-0.0.1-SNAPSHOT.jar"]